In [29]:
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, BitsAndBytesConfig, set_seed, EarlyStoppingCallback
from peft import LoraConfig
from trl import SFTTrainer
from datasets import load_dataset
import os
import torch
from tqdm import tqdm
import re
import editdistance
from sklearn.model_selection import KFold
import numpy as np
import random
import torch
from peft import PeftModel
import json

# Setup Environments

In [2]:
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

In [3]:
seed = 42

random.seed(seed)
torch.manual_seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)  # For multi-GPU
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
set_seed(seed)
os.environ['PYTHONHASHSEED'] = str(seed)

# Load Training Dataset

In [4]:
dataset = load_dataset("json", data_files="val_candidates_seed1_6_9_11_15_17_20_21_26_28_top1.json", split="train")
num_folds = 5
kf = KFold(n_splits=num_folds, shuffle=True, random_state=seed)

# LLM Configs

In [5]:
model_id = "meta-llama/Llama-3.2-3B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token # Llama has no pad token by default, eos is fine for Llama because it uses end of turn to stop chat generation
tokenizer.padding_side = "right" # Fix for fp16 training
tokenizer.pad_token_id = tokenizer.eos_token_id

peft_config = LoraConfig(
    r=16,       
    lora_alpha=16,
    lora_dropout=0.1,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
)

In [6]:
def format_chat_template(row):
    messages = [
        {
            "role": "system",
            # "content": "Your task is to perform automatic speech recognition. Below are multiple candidate transcriptions. Based on the transcription candidates, come up with a transcription that is most accurate, ensuring the transcription is contextually and grammatically correct. Focus on key differences in the candidates that change the meaning or correctness. Avoid selections with repetitive or nonsensical phrases. In cases of ambiguity, select the option that is most coherent and contextually sound. Respond with your refined transcription only, without any introductory text."
            # "content": "Your task is to perform automatic speech recognition. Below are a list of candidate transcriptions for a single spoken sentence. Identify the true transcription from the list. The candidates may contain phonetic errors (words that sound similar but are wrong). Use your knowledge of context, grammar, and common speech patterns to select the most likely original sentence. Choose EXACTLY one transcription from the list or a corrected version if all contain slight errors. Respond ONLY with the final text. Do not provide explanations, introductory text, or punctuation. Output lowercase only."
            "content": "Your task is to perform automatic speech recognition. Below are multiple candidate transcriptions predicted by different models. Choose the transcription that is most accurate, ensuring it is contextually and grammatically correct. Focus on key differences in the options that change the meaning or correctness. Avoid selections with repetitive or nonsensical phrases. In cases of ambiguity, select the option that is most coherent and contextually sound. Make sure to respond the complete chosen transcription exactly as it appears, word-for-word, no capitalization. Respond with the chosen transcription only, without any introductory text."
        },
        {
            "role": "user",
            "content": "\n".join([f"{cand}" for i, cand in enumerate(row["candidates"])])
        },
        {
            "role": "assistant",
            "content": row["ground_truth"]
        }
    ]
    row["text"] = tokenizer.apply_chat_template(messages, tokenize=False)
    return row

# Training

In [7]:
print(f"Starting {num_folds}-Fold Cross-Validation on {len(dataset)} samples...")

for fold_idx, (train_indices, val_indices) in enumerate(kf.split(dataset)):
    
    print(f"\n--- Starting Fold {fold_idx+1}/{num_folds} ---")

    train_dataset = dataset.select(train_indices)
    val_dataset = dataset.select(val_indices)

    train_dataset = train_dataset.map(format_chat_template)
    val_dataset = val_dataset.map(format_chat_template)

    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        # quantization_config=bnb_config,
        device_map="cuda:0",
        dtype=torch.float16
    )
    model.config.use_cache = False # Don't use during training
    model.config.pretraining_tp = 1 # Set to 1

    training_args = TrainingArguments(
        output_dir="./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold"+str(fold_idx+1),
        num_train_epochs=10.0,
        per_device_train_batch_size=4,
        gradient_accumulation_steps=4,
        # dataloader_drop_last=True,
        learning_rate=5e-5,
        weight_decay=0.1,
        fp16=True,  # Use mixed precision
        logging_dir="./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold"+str(fold_idx+1)+"/logs",
        logging_strategy="steps",
        logging_steps=18,
        save_strategy="steps",
        save_steps=18,   
        eval_strategy="steps",              
        eval_steps=18,                      
        per_device_eval_batch_size=32, 
        max_grad_norm=1.0,
        warmup_ratio=0.05,
        label_smoothing_factor=0.0,
        group_by_length=False, # Sorts samples by length for efficiency
        lr_scheduler_type="cosine",
        seed=seed,
        data_seed=seed,
        metric_for_best_model="eval_loss",
        load_best_model_at_end=True,
        greater_is_better=False,
    )

    trainer = SFTTrainer(
        model=model,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=5)],
        peft_config=peft_config,
        args=training_args,
    )

    trainer.train()

Starting 5-Fold Cross-Validation on 1426 samples...

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.52it/s]
The model is already on multiple devices. Skipping the move to device specified in `args`.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 128009}.

--- Starting Fold 2/5 ---

Map: 100%|██████████| 1141/1141 [00:00<00:00, 10636.71 examples/s]
Map: 100%|██████████| 285/285 [00:00<00:00, 15386.29 examples/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]
Adding EOS to train dataset: 100%|██████████| 1141/1141 [00:00<00:00, 38128.82 examples/s]
Tokenizing train dataset: 100%|██████████| 1141/1141 [00:00<00:00, 3509.82 examples/s]
Truncating train dataset: 100%|██████████| 1141/1141 [00:00<00:00, 273609.33 examples/s]
Adding EOS to eval dataset: 100%|██████████| 285/285 [00:00<00:00, 36135.93 examples/s]
Tokenizing eval dataset: 100%|██████████| 285/285 [00:00<00:00, 3849.53 examples/s]
Truncating eval dataset: 100%|██████████| 285/285 [00:00<00:00, 134705.50 examples/s]
The model is already on multiple devices. Skipping the move to device specified in `args`.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 128009}.

--- Starting Fold 3/5 ---

Map: 100%|██████████| 1141/1141 [00:00<00:00, 12287.51 examples/s]
Map: 100%|██████████| 285/285 [00:00<00:00, 15594.85 examples/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]
Adding EOS to train dataset: 100%|██████████| 1141/1141 [00:00<00:00, 37643.85 examples/s]
Tokenizing train dataset: 100%|██████████| 1141/1141 [00:00<00:00, 3565.69 examples/s]
Truncating train dataset: 100%|██████████| 1141/1141 [00:00<00:00, 286792.17 examples/s]
Adding EOS to eval dataset: 100%|██████████| 285/285 [00:00<00:00, 36524.59 examples/s]
Tokenizing eval dataset: 100%|██████████| 285/285 [00:00<00:00, 3730.11 examples/s]
Truncating eval dataset: 100%|██████████| 285/285 [00:00<00:00, 158769.64 examples/s]
The model is already on multiple devices. Skipping the move to device specified in `args`.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 128009}.

--- Starting Fold 4/5 ---

Map: 100%|██████████| 1141/1141 [00:00<00:00, 11779.11 examples/s]
Map: 100%|██████████| 285/285 [00:00<00:00, 12135.93 examples/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.57it/s]
Adding EOS to train dataset: 100%|██████████| 1141/1141 [00:00<00:00, 31964.55 examples/s]
Tokenizing train dataset: 100%|██████████| 1141/1141 [00:00<00:00, 3707.17 examples/s]
Truncating train dataset: 100%|██████████| 1141/1141 [00:00<00:00, 292649.72 examples/s]
Adding EOS to eval dataset: 100%|██████████| 285/285 [00:00<00:00, 37292.59 examples/s]
Tokenizing eval dataset: 100%|██████████| 285/285 [00:00<00:00, 3704.19 examples/s]
Truncating eval dataset: 100%|██████████| 285/285 [00:00<00:00, 130942.78 examples/s]
The model is already on multiple devices. Skipping the move to device specified in `args`.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 128009}.

--- Starting Fold 5/5 ---

Map: 100%|██████████| 1141/1141 [00:00<00:00, 11462.37 examples/s]
Map: 100%|██████████| 285/285 [00:00<00:00, 14569.77 examples/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]
Adding EOS to train dataset: 100%|██████████| 1141/1141 [00:00<00:00, 39751.65 examples/s]
Tokenizing train dataset: 100%|██████████| 1141/1141 [00:00<00:00, 3729.82 examples/s]
Truncating train dataset: 100%|██████████| 1141/1141 [00:00<00:00, 307366.79 examples/s]
Adding EOS to eval dataset: 100%|██████████| 285/285 [00:00<00:00, 37559.75 examples/s]
Tokenizing eval dataset: 100%|██████████| 285/285 [00:00<00:00, 3709.31 examples/s]
Truncating eval dataset: 100%|██████████| 285/285 [00:00<00:00, 143882.60 examples/s]
The model is already on multiple devices. Skipping the move to device specified in `args`.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 128009}.

# WER Evaluation

In [10]:
def remove_punctuation(sentence):

    sentence = re.sub(r'[^a-zA-Z\- \']', '', sentence)
    sentence = sentence.replace('- ', ' ').lower()
    sentence = sentence.replace('--', '').lower()
    sentence = sentence.replace(" '", "'").lower()
    sentence = sentence.strip()
    sentence = ' '.join([word for word in sentence.split() if word != ''])

    return sentence

def generate_predictions(model, tokenizer, val_dataset, batch_size=8):

    model.eval()
    
    tokenizer.padding_side = "left"
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
        tokenizer.pad_token_id = tokenizer.eos_token_id
    
    predictions = []
    ground_truths = []
    candidates_list = []
    
    device = next(model.parameters()).device

    formatted_prompts = []
    for sample in val_dataset:
        messages = [
            {
                "role": "system",
                "content": "Your task is to perform automatic speech recognition. Below are multiple candidate transcriptions predicted by different models. Choose the transcription that is most accurate, ensuring it is contextually and grammatically correct. Focus on key differences in the options that change the meaning or correctness. Avoid selections with repetitive or nonsensical phrases. In cases of ambiguity, select the option that is most coherent and contextually sound. Make sure to respond the complete chosen transcription exactly as it appears, word-for-word, no capitalization. Respond with the chosen transcription only, without any introductory text."
            },
            {
                "role": "user",
                "content": "\n".join(sample['candidates'])
            }
        ]
        prompt = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True  # This adds <|start_header_id|>assistant<|end_header_id|>
        )
        formatted_prompts.append(prompt)
        ground_truths.append(sample['ground_truth'].strip())
        candidates_list.append(sample['candidates'])

    for i in range(0, len(formatted_prompts), batch_size):
        batch_prompts = formatted_prompts[i : i + batch_size]
        inputs = tokenizer(
            batch_prompts, 
            return_tensors="pt", 
            padding=True,       # Pads to the longest seq in this batch
            truncation=True, 
            max_length=2048
        ).to(device)
        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=128,           # Limit response length
                use_cache=True,               # Enable cache for faster generation     
                pad_token_id=tokenizer.pad_token_id, 
                eos_token_id=tokenizer.eos_token_id,  
                # temperature=0.1,              # Low temperature for deterministic output
                # do_sample=True,               # Enable sampling for temperature
                do_sample=False,
                # top_p=0.9,                    # Nucleus sampling
                # repetition_penalty=1.1        # Prevent repetition
                repetition_penalty=1.0
            )
        generated_tokens = outputs[:, inputs["input_ids"].shape[1]:]
        decoded_batch = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)
        clean_batch = [pred.strip().lower() for pred in decoded_batch]
        predictions.extend(clean_batch)
    
    return predictions, ground_truths, candidates_list

In [ ]:
steps = np.arange(144, 594+18, 18).tolist()

for step_idx, step in enumerate(steps):

    prediction_all = []
    ground_truths_all = []
    print(f"--- Starting Step {step} ---")

    for fold_idx, (train_indices, val_indices) in enumerate(kf.split(dataset)):
        
        # print(f"--- Starting Fold {fold_idx+1}/{num_folds} ---")

        val_dataset = dataset.select(val_indices)

        model_id = "meta-llama/Llama-3.2-3B-Instruct"
        base_model = AutoModelForCausalLM.from_pretrained(
            model_id,
            device_map="cuda:0",
            torch_dtype=torch.float16
        )
        checkpoint_path = f"./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold{fold_idx+1}/checkpoint-{step}" 
        finetuned_model = PeftModel.from_pretrained(
            base_model,
            checkpoint_path,
            device_map="cuda:0"
        )
        finetuned_model.eval()

        # print(f"Loaded fine-tuned model from {checkpoint_path}")

        # tokenizer = trainer.tokenizer
        tokenizer = AutoTokenizer.from_pretrained(model_id)

        predictions_ft, ground_truths_ft, candidates_ft = generate_predictions(
            finetuned_model,  
            tokenizer,
            val_dataset,
            batch_size=16
        )

        prediction_all.extend(predictions_ft)
        ground_truths_all.extend(ground_truths_ft)

    results = []
    for i, (pred, gt) in enumerate(zip(prediction_all, ground_truths_all)):
        results.append({
            "id": i,
            "prediction": pred,
            "ground_truth": gt
        })
    output_file = f"./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/val_results/step_{step}.json"
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=2, ensure_ascii=False)

    total_true_length = 0
    total_edit_distance = 0

    for i in range(len(prediction_all)):
        true_sentence = remove_punctuation(ground_truths_all[i]).strip()
        pred_sentence = remove_punctuation(prediction_all[i]).strip()
        ed = editdistance.eval(true_sentence.split(), pred_sentence.split())
        total_edit_distance += ed
        total_true_length += len(true_sentence.split())

    print(f'Step {step} Aggregate Word Error Rate (WER): {100 * total_edit_distance / total_true_length:.2f}%')

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-144

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-144

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-144

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-144

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.53it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-144
Step 144 Aggregate Word Error Rate (WER): 3.32%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.56it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-162

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-162

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-162

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-162

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-162
Step 162 Aggregate Word Error Rate (WER): 3.27%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-180

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-180

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-180

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-180

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-180
Step 180 Aggregate Word Error Rate (WER): 3.29%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.63it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-198

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-198

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-198

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-198

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-198
Step 198 Aggregate Word Error Rate (WER): 3.29%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.57it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-216

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-216

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-216

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-216

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-216
Step 216 Aggregate Word Error Rate (WER): 3.24%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-234

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.63it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-234

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.55it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-234

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.56it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-234

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-234
Step 234 Aggregate Word Error Rate (WER): 3.24%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-252

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-252

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-252

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-252

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-252
Step 252 Aggregate Word Error Rate (WER): 3.24%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.56it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-270

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-270

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-270

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.55it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-270

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-270
Step 270 Aggregate Word Error Rate (WER): 3.21%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.63it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-288

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-288

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.57it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-288

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-288

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-288
Step 288 Aggregate Word Error Rate (WER): 3.22%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.57it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-306

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-306

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-306

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-306

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-306
Step 306 Aggregate Word Error Rate (WER): 3.30%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-324

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-324

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.57it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-324

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.63it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-324

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-324
Step 324 Aggregate Word Error Rate (WER): 3.29%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.53it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-342

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-342

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-342

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.63it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-342

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.57it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-342
Step 342 Aggregate Word Error Rate (WER): 3.30%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.63it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-360

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.63it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-360

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-360

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.57it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-360

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-360
Step 360 Aggregate Word Error Rate (WER): 3.25%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-378

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.63it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-378

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-378

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-378

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.57it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-378
Step 378 Aggregate Word Error Rate (WER): 3.25%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-396

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-396

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-396

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-396

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-396
Step 396 Aggregate Word Error Rate (WER): 3.24%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-414

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.63it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-414

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-414

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-414

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-414
Step 414 Aggregate Word Error Rate (WER): 3.21%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.51it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-432

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-432

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-432

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-432

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-432
Step 432 Aggregate Word Error Rate (WER): 3.19%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-450

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-450

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-450

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.55it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-450

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.63it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-450
Step 450 Aggregate Word Error Rate (WER): 3.17%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-468

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-468

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-468

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-468

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-468
Step 468 Aggregate Word Error Rate (WER): 3.17%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-486

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-486

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-486

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-486

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-486
Step 486 Aggregate Word Error Rate (WER): 3.19%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-504

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-504

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-504

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-504

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.56it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-504
Step 504 Aggregate Word Error Rate (WER): 3.20%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-522

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-522

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.63it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-522

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-522

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-522
Step 522 Aggregate Word Error Rate (WER): 3.20%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.57it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-540

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-540

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-540

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-540

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-540
Step 540 Aggregate Word Error Rate (WER): 3.16%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.63it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-558

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.55it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-558

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.57it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-558

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-558

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-558
Step 558 Aggregate Word Error Rate (WER): 3.14%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-576

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.56it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-576

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-576

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-576

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.56it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-576
Step 576 Aggregate Word Error Rate (WER): 3.14%

--- Starting Fold 1/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.56it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold1/checkpoint-594

--- Starting Fold 2/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.63it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold2/checkpoint-594

--- Starting Fold 3/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold3/checkpoint-594

--- Starting Fold 4/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.57it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold4/checkpoint-594

--- Starting Fold 5/5 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Loaded fine-tuned model from ./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold5/checkpoint-594
Step 594 Aggregate Word Error Rate (WER): 3.16%

In [31]:
steps = np.arange(144, 594+18, 18).tolist()

for step_idx, step in enumerate(steps):

    prediction_all = []
    ground_truths_all = []
    print(f"--- Starting Step {step} ---")

    for fold_idx, (train_indices, val_indices) in enumerate(kf.split(dataset)):
        
        # print(f"--- Starting Fold {fold_idx+1}/{num_folds} ---")

        val_dataset = dataset.select(val_indices)

        model_id = "meta-llama/Llama-3.2-3B-Instruct"
        base_model = AutoModelForCausalLM.from_pretrained(
            model_id,
            device_map="cuda:0",
            torch_dtype=torch.float16
        )
        checkpoint_path = f"./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/fold{fold_idx+1}/checkpoint-{step}" 
        finetuned_model = PeftModel.from_pretrained(
            base_model,
            checkpoint_path,
            device_map="cuda:0"
        )
        finetuned_model.eval()

        # print(f"Loaded fine-tuned model from {checkpoint_path}")

        # tokenizer = trainer.tokenizer
        tokenizer = AutoTokenizer.from_pretrained(model_id)

        predictions_ft, ground_truths_ft, candidates_ft = generate_predictions(
            finetuned_model,  
            tokenizer,
            val_dataset,
            batch_size=32
        )

        prediction_all.extend(predictions_ft)
        ground_truths_all.extend(ground_truths_ft)

    results = []
    for i, (pred, gt) in enumerate(zip(prediction_all, ground_truths_all)):
        results.append({
            "id": i,
            "prediction": pred,
            "ground_truth": gt
        })
    output_dir = "./Llama3.2-3B-Instruct_5fold_10epochs_rank16_10bestseeds/val_results"
    output_file = f"{output_dir}/step_{step}.json"
    os.makedirs(output_dir, exist_ok=True)
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=2, ensure_ascii=False)

    total_true_length = 0
    total_edit_distance = 0

    for i in range(len(prediction_all)):
        true_sentence = remove_punctuation(ground_truths_all[i]).strip()
        pred_sentence = remove_punctuation(prediction_all[i]).strip()
        ed = editdistance.eval(true_sentence.split(), pred_sentence.split())
        total_edit_distance += ed
        total_true_length += len(true_sentence.split())

    print(f'Step {step} Aggregate Word Error Rate (WER): {100 * total_edit_distance / total_true_length:.2f}%')

--- Starting Step 144 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.42it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Step 144 Aggregate Word Error Rate (WER): 3.32%
--- Starting Step 162 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.53it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.64it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Step 162 Aggregate Word Error Rate (WER): 3.28%
--- Starting Step 180 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.57it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]

Step 180 Aggregate Word Error Rate (WER): 3.29%
--- Starting Step 198 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.52it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.57it/s]

Step 198 Aggregate Word Error Rate (WER): 3.29%
--- Starting Step 216 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.57it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.56it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]

Step 216 Aggregate Word Error Rate (WER): 3.23%
--- Starting Step 234 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.57it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.56it/s]

Step 234 Aggregate Word Error Rate (WER): 3.24%
--- Starting Step 252 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.56it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.61it/s]

Step 252 Aggregate Word Error Rate (WER): 3.24%
--- Starting Step 270 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.60it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.58it/s]

Step 270 Aggregate Word Error Rate (WER): 3.21%
--- Starting Step 288 ---

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.57it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]

KeyboardInterrupt: